prompts:
  evaluation_prompt: "The following exercise consists of a structured input and the\
    \ student's generated fable.\n\nStructured Input:\nCharacter: {character}\nTrait:\
    \ {trait}\nSetting: {setting}\nConflict: {conflict}\nResolution: {resolution}\n\
    Moral: {moral}\n\nGenerated Fable:\n{generated_fab}\n\nTask:\n1. Evaluate the\
    \ fable based on these criteria:\n   - Grammar: Is the fable grammatically correct?\n\
    \   - Creativity: Does the fable demonstrate creative storytelling?\n   - Consistency:\
    \ Does the fable align with the structured input?\n\n2. Provide a guess for the\
    \ age group of the writer. Possible age groups:\n   A: 3 or under\n   B: 4-5\n\
    \   C: 6-7\n   D: 8-9\n   E: 10-12\n   F: 13-16\n\n3. Return your evaluation strictly\
    \ in the following JSON format:\n\n{{\n  \"Grammar\": \"x/10\",\n  \"Creativity\"\
    : \"x/10\",\n  \"Consistency\": \"x/10\",\n  \"Age group\": \"<age group guess>\"\
    \n}}\n\nThen, after returning the JSON block, add any additional comments you\
    \ have about the fable in plain text.\n"
  diversity_eval_prompt: Analyze the following dataset samples and assess their diversity.
    Consider factors such as variation in vocabulary, sentence structure, themes,
    named entities, and syntactic patterns. Provide a diversity score from 0 to 1
    (where 0 means highly repetitive and 1 means highly diverse). Identify any duplicated
    or highly similar entries and suggest improvements if needed. The output should
    be JSON-formatted which contains a "diversity_score" key.
parameters:
  character: The character of the fable (e.g., Fox)
  trait: The character's trait (e.g., Clever)
  setting: The setting of the fable (e.g., Forest)
  conflict: The conflict in the fable (e.g., Helping someone in need)
  resolution: The resolution of the fable (e.g., Reward)
  moral: The moral of the story (e.g., Kindness is rewarded)
  generated_fab: The fable generated by the model.
  output: 'The file path where evaluation results will be saved. Default: evaluation_results.json'
data:
- character: Rabbit
  trait: Brave
  setting: Forest
  conflict: Competing for food
  resolution: Punishment
  moral: Hard work pays off
  generated_fab: "Okay, so I need to create a fable based on the input provided. The\
    \ user has given a structure, with examples, so I should follow that closely.\
    \ Let me breakdown the input: \n\nCharacter: Rabbit  \nTrait: Brave  \nSetting:\
    \ Forest  \nConflict: Competing for food  \nResolution: Punishment  \nMoral: Hard\
    \ work pays off.\n\nWait, the example structure from the user had five specific\
    \ parts: Once there was a {trait} {character} in a {setting}. One day, it was\
    \ {conflict}. After much effort, {resolution}. Moral: {moral}. So I need to make\
    \ sure to include each part without adding extra.\n\nFirst, the wording should\
    \ be exactly as the structure requires. No deviations. The fable must start with\
    \ \"Once there was a...\" Then include the trait and character, followed by the\
    \ setting.\n\nConflict is about competing for food, and the resolution is punishment.\
    \ The moral is that hard work pays off.\n\nI need to form a coherent story that\
    \ flows naturally. Let's think about how a rabbit in a forest competing for food\
    \ leads to punishment, which then teaches that hard work is rewarded.\n\nHmm,\
    \ the rabbit is brave. Competing for food in the forest—maybe there's a limited\
    \ food source, like a river or a good hunting spot. The conflict is the competition,\
    \ so perhaps the rabbit is trying to get food but faces challenges.\n\nResolution\
    \ is punishment—maybe the rabbit overstepped and gets caught. But"
