system_prompt: >
    You are a world-class creative assistant that generates captivating and morally-driven fables based on structured inputs. 
    Each fable must be:
    • Imaginative and coherent.
    • Appropriate for a wide audience, including young readers.
    • Structured around a classic fable format (character, setting, conflict, resolution, and moral). 
    • Strictly adhering to the template:
    Once there was a {trait} {character} in a {setting}. 
    One day, it was {conflict}. After much effort, {resolution}.
    Moral: {moral}.

    When generating a fable, follow this exact structure without adding extra sections or deviating from the order. 
    Ensure the narrative is engaging and clearly presents the moral lesson at the end.


fable_prompt: >
    Create a fable based on the following structured input. The fable must follow this structure exactly:

    Once there was a {trait} {character} in a {setting}. 
    One day, it was {conflict}. After much effort, {resolution}.
    Moral: {moral}.

    Below are five examples to guide you:

    -------------------------
    Example 1
    -------------------------
    Input:
    Character: Fox
    Trait: Clever
    Setting: Forest
    Conflict: Helping someone in need
    Resolution: Reward
    Moral: Kindness is rewarded

    Fable:
    Once there was a clever fox in a forest. One day, it was helping a trapped bird escape from a hunter’s net. After much effort, the fox gnawed through the net and freed the bird. Grateful for its rescue, the bird led the fox to a hidden cache of berries.
    Moral: Kindness is rewarded.

    -------------------------
    Example 2
    -------------------------
    Input:
    Character: Lion
    Trait: Courageous
    Setting: Savanna
    Conflict: Protecting a smaller animal
    Resolution: Gains respect
    Moral: True strength lies in protecting others

    Fable:
    Once there was a courageous lion in the savanna. One day, it was protecting a lost fawn from prowling hyenas. After much effort, the lion chased off the hyenas and guided the fawn back to safety. Other animals admired the lion’s bravery and rallied behind it.
    Moral: True strength lies in protecting others.

    -------------------------
    Example 3
    -------------------------
    Input:
    Character: Crow
    Trait: Resourceful
    Setting: Orchard
    Conflict: Thirst in a dry season
    Resolution: Found a clever way
    Moral: Creativity solves problems

    Fable:
    Once there was a resourceful crow in an orchard. One day, it was thirsty during a long dry season. After much effort, the crow found a tall pitcher with water at the bottom and dropped small pebbles into it until the water rose high enough to drink.
    Moral: Creativity solves problems.

    -------------------------
    Example 4
    -------------------------
    Input:
    Character: Tortoise
    Trait: Patient
    Setting: Riverside
    Conflict: Crossing a dangerous bridge
    Resolution: Earned help from friends
    Moral: Patience and humility bring support

    Fable:
    Once there was a patient tortoise by the riverside. One day, it was crossing a broken bridge with swirling rapids below. After much effort, the tortoise inched carefully along until its friends arrived to steady the planks and guide it across.
    Moral: Patience and humility bring support.

    -------------------------
    Example 5
    -------------------------
    Input:
    Character: Monkey
    Trait: Curious
    Setting: Rainforest
    Conflict: Finding lost fruit
    Resolution: Shared discovery
    Moral: Sharing brings joy to all

    Fable:
    Once there was a curious monkey in a rainforest. One day, it was searching for its favorite fruit hidden high among the canopy leaves. After much effort, the monkey discovered the fruit and called other animals to share in the feast.
    Moral: Sharing brings joy to all.

    -------------------------
    Now use the input below to generate a new fable, following the exact structure:
    -------------------------
    Input:
    [Your new input goes here; for example:]
    Character: [X]
    Trait: [X]
    Setting: [X]
    Conflict: [X]
    Resolution: [X]
    Moral: [X]
    -------------------------

characters:
  - Rabbit
  - Fox
  - Squirrel

traits:
  - Brave
  - Greedy
  - Wise

settings:
  - Forest
  - River

conflicts:
  - Competing for food
  - Helping someone in need

resolutions:
  - Reward
  - Punishment

morals:
  - Kindness is rewarded
  - Hard work pays off