prompts:
  evaluation_prompt: |
    The following exercise consists of a structured input and the student's generated fable.
    Please provide your general assessment about the fable written by the student. Is it grammatically correct? Is it consistent with the beginning of the story?
    The input:
    Character: {character}
    Trait: {trait}
    Setting: {setting}
    Conflict: {conflict}
    Resolution: {resolution}
    Moral: {moral}

    The generated fable:
    {generated_fab}

    Then, please evaluate the generated fable based on the following criteria:
    1. Grammar: Is the fable grammatically correct?
    2. Creativity: Does the fable demonstrate creative storytelling?
    3. Consistency: Does the fable align with the structured input provided?
    Also, provide a guess for the age group of the writer. Choose from possible age groups: A: 3 or under. B: 4-5. C: 6-7. D: 8-9. E: 10-12. F: 13-16.

    Return your evaluation as follows:
    Grammar: x/10
    Creativity: x/10
    Consistency: x/10
    Age group: <age group guess>

parameters:
  character: "The character of the fable (e.g., Fox)"
  trait: "The character's trait (e.g., Clever)"
  setting: "The setting of the fable (e.g., Forest)"
  conflict: "The conflict in the fable (e.g., Helping someone in need)"
  resolution: "The resolution of the fable (e.g., Reward)"
  moral: "The moral of the story (e.g., Kindness is rewarded)"
  generated_fab: "The fable generated by the model."
  output: "The file path where evaluation results will be saved. Default: evaluation_results.json"

data:
  - character: "Fox"
    trait: "Clever"
    setting: "Forest"
    conflict: "Helping someone in need"
    resolution: "Reward"
    moral: "Kindness is rewarded"
    generated_fab: |
      Once there was a clever fox in a forest. One day, it was helping a trapped bird escape from a hunter's net. After much effort, the fox used its cleverness to gnaw through the net and free the bird. In gratitude, the bird led the fox to a hidden cache of food. Moral: Kindness is rewarded.

  - character: "Turtle"
    trait: "Persistent"
    setting: "Riverbank"
    conflict: "Crossing a dangerous stream"
    resolution: "Building a makeshift bridge"
    moral: "Perseverance leads to success"
    generated_fab: |
      Along the riverbank, a persistent turtle faced a challenge: a dangerous stream with strong currents that blocked its way to a lush meadow. Despite the danger, the turtle decided to find a solution. It began collecting sturdy sticks and stones, working tirelessly to construct a makeshift bridge. The other animals mocked its slow progress, but the turtle remained focused. After days of effort, the bridge was complete, and the turtle safely crossed the stream to the meadow. Its determination inspired others to overcome their own obstacles. Moral: Perseverance leads to success.
